---
- name: Delete Redis containers
  docker_container:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  with_items:
     - "{{ container_1_name }}"
     - "{{ container_2_name }}"

- name: Delete Redis bridge
  docker_network:
    name: redis_bridge
    state: absent
    force: yes
  ignore_errors: yes
